<?php

require_once 'propel/om/BaseObject.php';

require_once 'propel/om/Persistent.php';


include_once 'propel/util/Criteria.php';

include_once 'classes/OperationPeer.php';

/**
 * Base class that represents a row from the 'operation' table.
 *
 * List of operations (made of incomings and outgoings)
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 05:40:06
 *
 * @package classes.om
 */
abstract class BaseOperation extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var OperationPeer
	 */
	protected static $peer;


	/**
	 * The value for the operationid field.
	 * @var int
	 */
	protected $operationid;


	/**
	 * The value for the operationts field.
	 * @var int
	 */
	protected $operationts;


	/**
	 * The value for the operationdescription field.
	 * @var string
	 */
	protected $operationdescription;

	/**
	 * Collection to store aggregation of collOutgoings.
	 * @var array
	 */
	protected $collOutgoings;
	
	/**
	 * The criteria used to select the current contents of collOutgoings.
	 * @var Criteria
	 */
	private $lastOutgoingCriteria = null;

	/**
	 * Collection to store aggregation of collIncomings.
	 * @var array
	 */
	protected $collIncomings;
	
	/**
	 * The criteria used to select the current contents of collIncomings.
	 * @var Criteria
	 */
	private $lastIncomingCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [operationid] column value.
	 * Operation ID
	 * @return int
	 */
	public function getOperationid()
	{

		return $this->operationid;
	}

	/**
	 * Get the [optionally formatted] [operationts] column value.
	 * Operation date
	 * @param string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the integer unix timestamp will be returned.
	 * @return mixed Formatted date/time value as string or integer unix timestamp (if format is NULL).
	 * @throws PropelException - if unable to convert the date/time to timestamp.
	 */
	public function getOperationts($format = 'Y-m-d H:i:s')
	{

		if ($this->operationts === null || $this->operationts === '') {
			return null;
		} elseif (!is_int($this->operationts)) {
			// a non-timestamp value was set externally, so we convert it
			$ts = strtotime($this->operationts);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse value of [operationts] as date/time value: " . var_export($this->operationts, true));
			}
		} else {
			$ts = $this->operationts;
		}
		if ($format === null) {
			return $ts;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $ts);
		} else {
			return date($format, $ts);
		}
	}

	/**
	 * Get the [operationdescription] column value.
	 * Operation description
	 * @return string
	 */
	public function getOperationdescription()
	{

		return $this->operationdescription;
	}

	/**
	 * Set the value of [operationid] column.
	 * Operation ID
	 * @param int $v new value
	 * @return void
	 */
	public function setOperationid($v)
	{

		if ($this->operationid !== $v) {
			$this->operationid = $v;
			$this->modifiedColumns[] = OperationPeer::OPERATIONID;
		}

	} // setOperationid()

	/**
	 * Set the value of [operationts] column.
	 * Operation date
	 * @param int $v new value
	 * @return void
	 */
	public function setOperationts($v)
	{

		if ($v !== null && !is_int($v)) {
			$ts = strtotime($v);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse date/time value for [operationts] from input: " . var_export($v, true));
			}
		} else {
			$ts = $v;
		}
		if ($this->operationts !== $ts) {
			$this->operationts = $ts;
			$this->modifiedColumns[] = OperationPeer::OPERATIONTS;
		}

	} // setOperationts()

	/**
	 * Set the value of [operationdescription] column.
	 * Operation description
	 * @param string $v new value
	 * @return void
	 */
	public function setOperationdescription($v)
	{

		if ($this->operationdescription !== $v) {
			$this->operationdescription = $v;
			$this->modifiedColumns[] = OperationPeer::OPERATIONDESCRIPTION;
		}

	} // setOperationdescription()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (1-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param ResultSet $rs The ResultSet class with cursor advanced to desired record pos.
	 * @param int $startcol 1-based offset column which indicates which restultset column to start with.
	 * @return int next starting column
	 * @throws PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate(ResultSet $rs, $startcol = 1)
	{
		try {

			$this->operationid = $rs->getInt($startcol + 0);

			$this->operationts = $rs->getTimestamp($startcol + 1, null);

			$this->operationdescription = $rs->getString($startcol + 2);

			$this->resetModified();

			$this->setNew(false);

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = OperationPeer::NUM_COLUMNS - OperationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Operation object", $e);
		}
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param Connection $con
	 * @return void
	 * @throws PropelException
	 * @see BaseObject::setDeleted()
	 * @see BaseObject::isDeleted()
	 */
	public function delete($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(OperationPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			OperationPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.  If the object is new,
	 * it inserts it; otherwise an update is performed.  This method
	 * wraps the doSave() worker method in a transaction.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see doSave()
	 */
	public function save($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(OperationPeer::DATABASE_NAME);
		}
		
		try {
			$con->begin();
			$affectedRows = $this->doSave($con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.
	 * 
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see save()
	 */
	protected function doSave($con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows	
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;
	

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = OperationPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which 
										 // should always be true here (even though technically 
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setOperationid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += OperationPeer::doUpdate($this, $con);
				}
				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collOutgoings !== null) {
				foreach($this->collOutgoings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collIncomings !== null) {
				foreach($this->collIncomings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;
		}
		return $affectedRows;
	} // doSave()

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param mixed $columns Column name or an array of column names.
	 *
	 * @return mixed <code>true</code> if all columns pass validation
	 *			  or an array of <code>ValidationFailed</code> objects for columns that fail.
	 * @see doValidate()
	 */
	public function validate($columns = null)
	{
	  if ($columns) {
		return OperationPeer::doValidate($this, $columns);
	  }
		return $this->doValidate();
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate()
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = OperationPeer::doValidate($this)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collOutgoings !== null) {
					foreach($this->collOutgoings as $referrerFK) {
						if (($retval = $referrerFK->validate()) !== true) {
							$failureMap = array_merge($failureMap, $retval);
						}
					}
				}

				if ($this->collIncomings !== null) {
					foreach($this->collIncomings as $referrerFK) {
						if (($retval = $referrerFK->validate()) !== true) {
							$failureMap = array_merge($failureMap, $retval);
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(OperationPeer::DATABASE_NAME);

		if ($this->isColumnModified(OperationPeer::OPERATIONID)) $criteria->add(OperationPeer::OPERATIONID, $this->operationid);
		if ($this->isColumnModified(OperationPeer::OPERATIONTS)) $criteria->add(OperationPeer::OPERATIONTS, $this->operationts);
		if ($this->isColumnModified(OperationPeer::OPERATIONDESCRIPTION)) $criteria->add(OperationPeer::OPERATIONDESCRIPTION, $this->operationdescription);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(OperationPeer::DATABASE_NAME);

		$criteria->add(OperationPeer::OPERATIONID, $this->operationid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return int
	 */
	public function getPrimaryKey()
	{
		return $this->getOperationid();
	}

	/**
	 * Generic method to set the primary key (operationid column).
	 *
	 * @param int $key Primary key.
	 * @return void
	 */
	public function setPrimaryKey($key)
	{
		$this->setOperationid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param object $copyObj An object of Operation (or compatible) type.
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setOperationts($this->operationts);

		$copyObj->setOperationdescription($this->operationdescription);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach($this->getOutgoings() as $relObj) {
				$copyObj->addOutgoing($relObj->copy($deepCopy));
			}

			foreach($this->getIncomings() as $relObj) {
				$copyObj->addIncoming($relObj->copy($deepCopy));
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setOperationid(NULL); // this is a pkey column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return Operation Clone of current object.
	 * @throws PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return OperationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new OperationPeer();
		}
		return self::$peer;
	}

	/**
	 * Temporary storage of collOutgoings to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return void
	 */
	public function initOutgoings()
	{
		if ($this->collOutgoings === null) {
			$this->collOutgoings = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Operation has previously
	 * been saved, it will retrieve related Outgoings from storage.
	 * If this Operation is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param Connection $con
	 * @param Criteria $criteria
	 * @throws PropelException
	 */
	public function getOutgoings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoings === null) {
			if ($this->isNew()) {
			   $this->collOutgoings = array();
			} else {

				$criteria->add(OutgoingPeer::OPERATIONIDFK, $this->getOperationid());

				OutgoingPeer::addSelectColumns($criteria);
				$this->collOutgoings = OutgoingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OutgoingPeer::OPERATIONIDFK, $this->getOperationid());

				OutgoingPeer::addSelectColumns($criteria);
				if (!isset($this->lastOutgoingCriteria) || !$this->lastOutgoingCriteria->equals($criteria)) {
					$this->collOutgoings = OutgoingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOutgoingCriteria = $criteria;
		return $this->collOutgoings;
	}

	/**
	 * Returns the number of related Outgoings.
	 *
	 * @param Criteria $criteria
	 * @param Connection $con
	 * @throws PropelException
	 */
	public function countOutgoings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(OutgoingPeer::OPERATIONIDFK, $this->getOperationid());

		return OutgoingPeer::doCount($criteria, $con);
	}

	/**
	 * Method called to associate a Outgoing object to this object
	 * through the Outgoing foreign key attribute
	 *
	 * @param Outgoing $l Outgoing
	 * @return void
	 * @throws PropelException
	 */
	public function addOutgoing(Outgoing $l)
	{
		$this->collOutgoings[] = $l;
		$l->setOperation($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Operation is new, it will return
	 * an empty collection; or if this Operation has previously
	 * been saved, it will retrieve related Outgoings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Operation.
	 */
	public function getOutgoingsJoinPerson($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoings === null) {
			if ($this->isNew()) {
				$this->collOutgoings = array();
			} else {

				$criteria->add(OutgoingPeer::OPERATIONIDFK, $this->getOperationid());

				$this->collOutgoings = OutgoingPeer::doSelectJoinPerson($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OutgoingPeer::OPERATIONIDFK, $this->getOperationid());

			if (!isset($this->lastOutgoingCriteria) || !$this->lastOutgoingCriteria->equals($criteria)) {
				$this->collOutgoings = OutgoingPeer::doSelectJoinPerson($criteria, $con);
			}
		}
		$this->lastOutgoingCriteria = $criteria;

		return $this->collOutgoings;
	}

	/**
	 * Temporary storage of collIncomings to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return void
	 */
	public function initIncomings()
	{
		if ($this->collIncomings === null) {
			$this->collIncomings = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Operation has previously
	 * been saved, it will retrieve related Incomings from storage.
	 * If this Operation is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param Connection $con
	 * @param Criteria $criteria
	 * @throws PropelException
	 */
	public function getIncomings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncomings === null) {
			if ($this->isNew()) {
			   $this->collIncomings = array();
			} else {

				$criteria->add(IncomingPeer::OPERATIONIDFK, $this->getOperationid());

				IncomingPeer::addSelectColumns($criteria);
				$this->collIncomings = IncomingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(IncomingPeer::OPERATIONIDFK, $this->getOperationid());

				IncomingPeer::addSelectColumns($criteria);
				if (!isset($this->lastIncomingCriteria) || !$this->lastIncomingCriteria->equals($criteria)) {
					$this->collIncomings = IncomingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastIncomingCriteria = $criteria;
		return $this->collIncomings;
	}

	/**
	 * Returns the number of related Incomings.
	 *
	 * @param Criteria $criteria
	 * @param Connection $con
	 * @throws PropelException
	 */
	public function countIncomings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(IncomingPeer::OPERATIONIDFK, $this->getOperationid());

		return IncomingPeer::doCount($criteria, $con);
	}

	/**
	 * Method called to associate a Incoming object to this object
	 * through the Incoming foreign key attribute
	 *
	 * @param Incoming $l Incoming
	 * @return void
	 * @throws PropelException
	 */
	public function addIncoming(Incoming $l)
	{
		$this->collIncomings[] = $l;
		$l->setOperation($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Operation is new, it will return
	 * an empty collection; or if this Operation has previously
	 * been saved, it will retrieve related Incomings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Operation.
	 */
	public function getIncomingsJoinPerson($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncomings === null) {
			if ($this->isNew()) {
				$this->collIncomings = array();
			} else {

				$criteria->add(IncomingPeer::OPERATIONIDFK, $this->getOperationid());

				$this->collIncomings = IncomingPeer::doSelectJoinPerson($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(IncomingPeer::OPERATIONIDFK, $this->getOperationid());

			if (!isset($this->lastIncomingCriteria) || !$this->lastIncomingCriteria->equals($criteria)) {
				$this->collIncomings = IncomingPeer::doSelectJoinPerson($criteria, $con);
			}
		}
		$this->lastIncomingCriteria = $criteria;

		return $this->collIncomings;
	}

} // BaseOperation
