<?php

require_once 'propel/om/BaseObject.php';

require_once 'propel/om/Persistent.php';


include_once 'propel/util/Criteria.php';

include_once 'classes/PersonPeer.php';

/**
 * Base class that represents a row from the 'person' table.
 *
 * List of person in the community
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 05:40:06
 *
 * @package classes.om
 */
abstract class BasePerson extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var PersonPeer
	 */
	protected static $peer;


	/**
	 * The value for the personid field.
	 * @var int
	 */
	protected $personid;


	/**
	 * The value for the personname field.
	 * @var string
	 */
	protected $personname;

	/**
	 * Collection to store aggregation of collOutgoings.
	 * @var array
	 */
	protected $collOutgoings;
	
	/**
	 * The criteria used to select the current contents of collOutgoings.
	 * @var Criteria
	 */
	private $lastOutgoingCriteria = null;

	/**
	 * Collection to store aggregation of collIncomings.
	 * @var array
	 */
	protected $collIncomings;
	
	/**
	 * The criteria used to select the current contents of collIncomings.
	 * @var Criteria
	 */
	private $lastIncomingCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [personid] column value.
	 * Person ID
	 * @return int
	 */
	public function getPersonid()
	{

		return $this->personid;
	}

	/**
	 * Get the [personname] column value.
	 * Person name
	 * @return string
	 */
	public function getPersonname()
	{

		return $this->personname;
	}

	/**
	 * Set the value of [personid] column.
	 * Person ID
	 * @param int $v new value
	 * @return void
	 */
	public function setPersonid($v)
	{

		if ($this->personid !== $v) {
			$this->personid = $v;
			$this->modifiedColumns[] = PersonPeer::PERSONID;
		}

	} // setPersonid()

	/**
	 * Set the value of [personname] column.
	 * Person name
	 * @param string $v new value
	 * @return void
	 */
	public function setPersonname($v)
	{

		if ($this->personname !== $v) {
			$this->personname = $v;
			$this->modifiedColumns[] = PersonPeer::PERSONNAME;
		}

	} // setPersonname()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (1-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param ResultSet $rs The ResultSet class with cursor advanced to desired record pos.
	 * @param int $startcol 1-based offset column which indicates which restultset column to start with.
	 * @return int next starting column
	 * @throws PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate(ResultSet $rs, $startcol = 1)
	{
		try {

			$this->personid = $rs->getInt($startcol + 0);

			$this->personname = $rs->getString($startcol + 1);

			$this->resetModified();

			$this->setNew(false);

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 2; // 2 = PersonPeer::NUM_COLUMNS - PersonPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Person object", $e);
		}
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param Connection $con
	 * @return void
	 * @throws PropelException
	 * @see BaseObject::setDeleted()
	 * @see BaseObject::isDeleted()
	 */
	public function delete($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			PersonPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.  If the object is new,
	 * it inserts it; otherwise an update is performed.  This method
	 * wraps the doSave() worker method in a transaction.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see doSave()
	 */
	public function save($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonPeer::DATABASE_NAME);
		}
		
		try {
			$con->begin();
			$affectedRows = $this->doSave($con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.
	 * 
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see save()
	 */
	protected function doSave($con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows	
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;
	

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PersonPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which 
										 // should always be true here (even though technically 
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setPersonid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PersonPeer::doUpdate($this, $con);
				}
				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collOutgoings !== null) {
				foreach($this->collOutgoings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collIncomings !== null) {
				foreach($this->collIncomings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;
		}
		return $affectedRows;
	} // doSave()

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param mixed $columns Column name or an array of column names.
	 *
	 * @return mixed <code>true</code> if all columns pass validation
	 *			  or an array of <code>ValidationFailed</code> objects for columns that fail.
	 * @see doValidate()
	 */
	public function validate($columns = null)
	{
	  if ($columns) {
		return PersonPeer::doValidate($this, $columns);
	  }
		return $this->doValidate();
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate()
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PersonPeer::doValidate($this)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collOutgoings !== null) {
					foreach($this->collOutgoings as $referrerFK) {
						if (($retval = $referrerFK->validate()) !== true) {
							$failureMap = array_merge($failureMap, $retval);
						}
					}
				}

				if ($this->collIncomings !== null) {
					foreach($this->collIncomings as $referrerFK) {
						if (($retval = $referrerFK->validate()) !== true) {
							$failureMap = array_merge($failureMap, $retval);
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PersonPeer::DATABASE_NAME);

		if ($this->isColumnModified(PersonPeer::PERSONID)) $criteria->add(PersonPeer::PERSONID, $this->personid);
		if ($this->isColumnModified(PersonPeer::PERSONNAME)) $criteria->add(PersonPeer::PERSONNAME, $this->personname);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PersonPeer::DATABASE_NAME);

		$criteria->add(PersonPeer::PERSONID, $this->personid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return int
	 */
	public function getPrimaryKey()
	{
		return $this->getPersonid();
	}

	/**
	 * Generic method to set the primary key (personid column).
	 *
	 * @param int $key Primary key.
	 * @return void
	 */
	public function setPrimaryKey($key)
	{
		$this->setPersonid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param object $copyObj An object of Person (or compatible) type.
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPersonname($this->personname);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach($this->getOutgoings() as $relObj) {
				$copyObj->addOutgoing($relObj->copy($deepCopy));
			}

			foreach($this->getIncomings() as $relObj) {
				$copyObj->addIncoming($relObj->copy($deepCopy));
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setPersonid(NULL); // this is a pkey column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return Person Clone of current object.
	 * @throws PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return PersonPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PersonPeer();
		}
		return self::$peer;
	}

	/**
	 * Temporary storage of collOutgoings to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return void
	 */
	public function initOutgoings()
	{
		if ($this->collOutgoings === null) {
			$this->collOutgoings = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person has previously
	 * been saved, it will retrieve related Outgoings from storage.
	 * If this Person is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param Connection $con
	 * @param Criteria $criteria
	 * @throws PropelException
	 */
	public function getOutgoings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoings === null) {
			if ($this->isNew()) {
			   $this->collOutgoings = array();
			} else {

				$criteria->add(OutgoingPeer::PERSONIDFK, $this->getPersonid());

				OutgoingPeer::addSelectColumns($criteria);
				$this->collOutgoings = OutgoingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OutgoingPeer::PERSONIDFK, $this->getPersonid());

				OutgoingPeer::addSelectColumns($criteria);
				if (!isset($this->lastOutgoingCriteria) || !$this->lastOutgoingCriteria->equals($criteria)) {
					$this->collOutgoings = OutgoingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOutgoingCriteria = $criteria;
		return $this->collOutgoings;
	}

	/**
	 * Returns the number of related Outgoings.
	 *
	 * @param Criteria $criteria
	 * @param Connection $con
	 * @throws PropelException
	 */
	public function countOutgoings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(OutgoingPeer::PERSONIDFK, $this->getPersonid());

		return OutgoingPeer::doCount($criteria, $con);
	}

	/**
	 * Method called to associate a Outgoing object to this object
	 * through the Outgoing foreign key attribute
	 *
	 * @param Outgoing $l Outgoing
	 * @return void
	 * @throws PropelException
	 */
	public function addOutgoing(Outgoing $l)
	{
		$this->collOutgoings[] = $l;
		$l->setPerson($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person is new, it will return
	 * an empty collection; or if this Person has previously
	 * been saved, it will retrieve related Outgoings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Person.
	 */
	public function getOutgoingsJoinOperation($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseOutgoingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoings === null) {
			if ($this->isNew()) {
				$this->collOutgoings = array();
			} else {

				$criteria->add(OutgoingPeer::PERSONIDFK, $this->getPersonid());

				$this->collOutgoings = OutgoingPeer::doSelectJoinOperation($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OutgoingPeer::PERSONIDFK, $this->getPersonid());

			if (!isset($this->lastOutgoingCriteria) || !$this->lastOutgoingCriteria->equals($criteria)) {
				$this->collOutgoings = OutgoingPeer::doSelectJoinOperation($criteria, $con);
			}
		}
		$this->lastOutgoingCriteria = $criteria;

		return $this->collOutgoings;
	}

	/**
	 * Temporary storage of collIncomings to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return void
	 */
	public function initIncomings()
	{
		if ($this->collIncomings === null) {
			$this->collIncomings = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person has previously
	 * been saved, it will retrieve related Incomings from storage.
	 * If this Person is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param Connection $con
	 * @param Criteria $criteria
	 * @throws PropelException
	 */
	public function getIncomings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncomings === null) {
			if ($this->isNew()) {
			   $this->collIncomings = array();
			} else {

				$criteria->add(IncomingPeer::PERSONIDFK, $this->getPersonid());

				IncomingPeer::addSelectColumns($criteria);
				$this->collIncomings = IncomingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(IncomingPeer::PERSONIDFK, $this->getPersonid());

				IncomingPeer::addSelectColumns($criteria);
				if (!isset($this->lastIncomingCriteria) || !$this->lastIncomingCriteria->equals($criteria)) {
					$this->collIncomings = IncomingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastIncomingCriteria = $criteria;
		return $this->collIncomings;
	}

	/**
	 * Returns the number of related Incomings.
	 *
	 * @param Criteria $criteria
	 * @param Connection $con
	 * @throws PropelException
	 */
	public function countIncomings($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(IncomingPeer::PERSONIDFK, $this->getPersonid());

		return IncomingPeer::doCount($criteria, $con);
	}

	/**
	 * Method called to associate a Incoming object to this object
	 * through the Incoming foreign key attribute
	 *
	 * @param Incoming $l Incoming
	 * @return void
	 * @throws PropelException
	 */
	public function addIncoming(Incoming $l)
	{
		$this->collIncomings[] = $l;
		$l->setPerson($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Person is new, it will return
	 * an empty collection; or if this Person has previously
	 * been saved, it will retrieve related Incomings from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Person.
	 */
	public function getIncomingsJoinOperation($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'classes/om/BaseIncomingPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncomings === null) {
			if ($this->isNew()) {
				$this->collIncomings = array();
			} else {

				$criteria->add(IncomingPeer::PERSONIDFK, $this->getPersonid());

				$this->collIncomings = IncomingPeer::doSelectJoinOperation($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(IncomingPeer::PERSONIDFK, $this->getPersonid());

			if (!isset($this->lastIncomingCriteria) || !$this->lastIncomingCriteria->equals($criteria)) {
				$this->collIncomings = IncomingPeer::doSelectJoinOperation($criteria, $con);
			}
		}
		$this->lastIncomingCriteria = $criteria;

		return $this->collIncomings;
	}

} // BasePerson
