<?php

require_once 'propel/om/BaseObject.php';

require_once 'propel/om/Persistent.php';


include_once 'propel/util/Criteria.php';

include_once 'classes/OutgoingPeer.php';

/**
 * Base class that represents a row from the 'outgoing' table.
 *
 * What is consumed by the community
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 05:40:06
 *
 * @package classes.om
 */
abstract class BaseOutgoing extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var OutgoingPeer
	 */
	protected static $peer;


	/**
	 * The value for the outid field.
	 * @var int
	 */
	protected $outid;


	/**
	 * The value for the outweight field.
	 * @var double
	 */
	protected $outweight;


	/**
	 * The value for the operationidfk field.
	 * @var int
	 */
	protected $operationidfk;


	/**
	 * The value for the personidfk field.
	 * @var int
	 */
	protected $personidfk;

	/**
	 * @var Operation
	 */
	protected $aOperation;

	/**
	 * @var Person
	 */
	protected $aPerson;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [outid] column value.
	 * Outgoing ID
	 * @return int
	 */
	public function getOutid()
	{

		return $this->outid;
	}

	/**
	 * Get the [outweight] column value.
	 * Weight applied to the person
	 * @return double
	 */
	public function getOutweight()
	{

		return $this->outweight;
	}

	/**
	 * Get the [operationidfk] column value.
	 * Operation foreign key
	 * @return int
	 */
	public function getOperationidfk()
	{

		return $this->operationidfk;
	}

	/**
	 * Get the [personidfk] column value.
	 * Person foreign key
	 * @return int
	 */
	public function getPersonidfk()
	{

		return $this->personidfk;
	}

	/**
	 * Set the value of [outid] column.
	 * Outgoing ID
	 * @param int $v new value
	 * @return void
	 */
	public function setOutid($v)
	{

		if ($this->outid !== $v) {
			$this->outid = $v;
			$this->modifiedColumns[] = OutgoingPeer::OUTID;
		}

	} // setOutid()

	/**
	 * Set the value of [outweight] column.
	 * Weight applied to the person
	 * @param double $v new value
	 * @return void
	 */
	public function setOutweight($v)
	{

		if ($this->outweight !== $v) {
			$this->outweight = $v;
			$this->modifiedColumns[] = OutgoingPeer::OUTWEIGHT;
		}

	} // setOutweight()

	/**
	 * Set the value of [operationidfk] column.
	 * Operation foreign key
	 * @param int $v new value
	 * @return void
	 */
	public function setOperationidfk($v)
	{

		if ($this->operationidfk !== $v) {
			$this->operationidfk = $v;
			$this->modifiedColumns[] = OutgoingPeer::OPERATIONIDFK;
		}

		if ($this->aOperation !== null && $this->aOperation->getOperationid() !== $v) {
			$this->aOperation = null;
		}		

	} // setOperationidfk()

	/**
	 * Set the value of [personidfk] column.
	 * Person foreign key
	 * @param int $v new value
	 * @return void
	 */
	public function setPersonidfk($v)
	{

		if ($this->personidfk !== $v) {
			$this->personidfk = $v;
			$this->modifiedColumns[] = OutgoingPeer::PERSONIDFK;
		}

		if ($this->aPerson !== null && $this->aPerson->getPersonid() !== $v) {
			$this->aPerson = null;
		}		

	} // setPersonidfk()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (1-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param ResultSet $rs The ResultSet class with cursor advanced to desired record pos.
	 * @param int $startcol 1-based offset column which indicates which restultset column to start with.
	 * @return int next starting column
	 * @throws PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate(ResultSet $rs, $startcol = 1)
	{
		try {

			$this->outid = $rs->getInt($startcol + 0);

			$this->outweight = $rs->getFloat($startcol + 1);

			$this->operationidfk = $rs->getInt($startcol + 2);

			$this->personidfk = $rs->getInt($startcol + 3);

			$this->resetModified();

			$this->setNew(false);

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = OutgoingPeer::NUM_COLUMNS - OutgoingPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Outgoing object", $e);
		}
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param Connection $con
	 * @return void
	 * @throws PropelException
	 * @see BaseObject::setDeleted()
	 * @see BaseObject::isDeleted()
	 */
	public function delete($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(OutgoingPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			OutgoingPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.  If the object is new,
	 * it inserts it; otherwise an update is performed.  This method
	 * wraps the doSave() worker method in a transaction.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see doSave()
	 */
	public function save($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(OutgoingPeer::DATABASE_NAME);
		}
		
		try {
			$con->begin();
			$affectedRows = $this->doSave($con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.
	 * 
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param Connection $con
	 * @return int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws PropelException
	 * @see save()
	 */
	protected function doSave($con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows	
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aOperation !== null) {
				if ($this->aOperation->isModified()) {
					$affectedRows += $this->aOperation->save($con);
				}
				$this->setOperation($this->aOperation);
			}

			if ($this->aPerson !== null) {
				if ($this->aPerson->isModified()) {
					$affectedRows += $this->aPerson->save($con);
				}
				$this->setPerson($this->aPerson);
			}
	

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = OutgoingPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which 
										 // should always be true here (even though technically 
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setOutid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += OutgoingPeer::doUpdate($this, $con);
				}
				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;
		}
		return $affectedRows;
	} // doSave()

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param mixed $columns Column name or an array of column names.
	 *
	 * @return mixed <code>true</code> if all columns pass validation
	 *			  or an array of <code>ValidationFailed</code> objects for columns that fail.
	 * @see doValidate()
	 */
	public function validate($columns = null)
	{
	  if ($columns) {
		return OutgoingPeer::doValidate($this, $columns);
	  }
		return $this->doValidate();
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate()
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aOperation !== null) {
				if (($retval = $this->aOperation->validate()) !== true) {
					$failureMap = array_merge($failureMap, $retval);
				}
			}

			if ($this->aPerson !== null) {
				if (($retval = $this->aPerson->validate()) !== true) {
					$failureMap = array_merge($failureMap, $retval);
				}
			}


			if (($retval = OutgoingPeer::doValidate($this)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(OutgoingPeer::DATABASE_NAME);

		if ($this->isColumnModified(OutgoingPeer::OUTID)) $criteria->add(OutgoingPeer::OUTID, $this->outid);
		if ($this->isColumnModified(OutgoingPeer::OUTWEIGHT)) $criteria->add(OutgoingPeer::OUTWEIGHT, $this->outweight);
		if ($this->isColumnModified(OutgoingPeer::OPERATIONIDFK)) $criteria->add(OutgoingPeer::OPERATIONIDFK, $this->operationidfk);
		if ($this->isColumnModified(OutgoingPeer::PERSONIDFK)) $criteria->add(OutgoingPeer::PERSONIDFK, $this->personidfk);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(OutgoingPeer::DATABASE_NAME);

		$criteria->add(OutgoingPeer::OUTID, $this->outid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return int
	 */
	public function getPrimaryKey()
	{
		return $this->getOutid();
	}

	/**
	 * Generic method to set the primary key (outid column).
	 *
	 * @param int $key Primary key.
	 * @return void
	 */
	public function setPrimaryKey($key)
	{
		$this->setOutid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param object $copyObj An object of Outgoing (or compatible) type.
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setOutweight($this->outweight);

		$copyObj->setOperationidfk($this->operationidfk);

		$copyObj->setPersonidfk($this->personidfk);


		$copyObj->setNew(true);

		$copyObj->setOutid(NULL); // this is a pkey column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 * 
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return Outgoing Clone of current object.
	 * @throws PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return OutgoingPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new OutgoingPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Operation object.
	 *
	 * @param Operation $v
	 * @return void
	 * @throws PropelException
	 */
	public function setOperation($v)
	{


		if ($v === null) {
			$this->setOperationidfk(NULL);
		} else {
			$this->setOperationidfk($v->getOperationid());
		}


		$this->aOperation = $v;
	}


	/**
	 * Get the associated Operation object
	 *
	 * @param Connection Optional Connection object.
	 * @return Operation The associated Operation object.
	 * @throws PropelException
	 */
	public function getOperation($con = null)
	{
		// include the related Peer class
		include_once 'classes/om/BaseOperationPeer.php';

		if ($this->aOperation === null && ($this->operationidfk !== null)) {

			$this->aOperation = OperationPeer::retrieveByPK($this->operationidfk, $con);
					
			/* The following can be used instead of the line above to
			   guarantee the related object contains a reference
			   to this object, but this level of coupling
			   may be undesirable in many circumstances.
			   As it can lead to a db query with many results that may
			   never be used.
			   $obj = OperationPeer::retrieveByPK($this->operationidfk, $con);
			   $obj->addOperations($this);
			 */
		}
		return $this->aOperation;
	}

	/**
	 * Declares an association between this object and a Person object.
	 *
	 * @param Person $v
	 * @return void
	 * @throws PropelException
	 */
	public function setPerson($v)
	{


		if ($v === null) {
			$this->setPersonidfk(NULL);
		} else {
			$this->setPersonidfk($v->getPersonid());
		}


		$this->aPerson = $v;
	}


	/**
	 * Get the associated Person object
	 *
	 * @param Connection Optional Connection object.
	 * @return Person The associated Person object.
	 * @throws PropelException
	 */
	public function getPerson($con = null)
	{
		// include the related Peer class
		include_once 'classes/om/BasePersonPeer.php';

		if ($this->aPerson === null && ($this->personidfk !== null)) {

			$this->aPerson = PersonPeer::retrieveByPK($this->personidfk, $con);
					
			/* The following can be used instead of the line above to
			   guarantee the related object contains a reference
			   to this object, but this level of coupling
			   may be undesirable in many circumstances.
			   As it can lead to a db query with many results that may
			   never be used.
			   $obj = PersonPeer::retrieveByPK($this->personidfk, $con);
			   $obj->addPersons($this);
			 */
		}
		return $this->aPerson;
	}

} // BaseOutgoing
