<?php
		
require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'incoming' table to 'money' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 05:40:06
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an 
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive 
 * (i.e. if it's a text column type).
 *
 * @package classes.map
 */	
class IncomingMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'classes.map.IncomingMapBuilder';	

    /**
     * The database map.
     */
    private $dbMap;

	/**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return boolean true if this DatabaseMapBuilder is built, false otherwise.
     */
    public function isBuilt()
    {
        return ($this->dbMap !== null);
    }

	/**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public function getDatabaseMap()
    {
        return $this->dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
	 * @return void
     * @throws PropelException
     */
    public function doBuild()
    {
		$this->dbMap = Propel::getDatabaseMap('money');
		
		$tMap = $this->dbMap->addTable('incoming');
		$tMap->setPhpName('Incoming');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('INID', 'Inid', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('INAMOUNT', 'Inamount', 'double', CreoleTypes::FLOAT, false, null);

		$tMap->addForeignKey('OPERATIONIDFK', 'Operationidfk', 'int', CreoleTypes::INTEGER, 'operation', 'OPERATIONID', true, null);

		$tMap->addForeignKey('PERSONIDFK', 'Personidfk', 'int', CreoleTypes::INTEGER, 'person', 'PERSONID', true, null);
				
    } // doBuild()

} // IncomingMapBuilder
