<?php
		
require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'person' table to 'money' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 05:40:06
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an 
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive 
 * (i.e. if it's a text column type).
 *
 * @package classes.map
 */	
class PersonMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'classes.map.PersonMapBuilder';	

    /**
     * The database map.
     */
    private $dbMap;

	/**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return boolean true if this DatabaseMapBuilder is built, false otherwise.
     */
    public function isBuilt()
    {
        return ($this->dbMap !== null);
    }

	/**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public function getDatabaseMap()
    {
        return $this->dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
	 * @return void
     * @throws PropelException
     */
    public function doBuild()
    {
		$this->dbMap = Propel::getDatabaseMap('money');
		
		$tMap = $this->dbMap->addTable('person');
		$tMap->setPhpName('Person');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('PERSONID', 'Personid', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('PERSONNAME', 'Personname', 'string', CreoleTypes::VARCHAR, true, 255);
				
    } // doBuild()

} // PersonMapBuilder
