<?php

namespace Kalkuli\ServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OutgoingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoingRepository extends EntityRepository
{
}