<?php

  // include base peer class
  require_once 'classes/om/BaseOperationPeer.php';
  
  // include object class
  include_once 'classes/Operation.php';


/**
 * Skeleton subclass for performing query and update operations on the 'operation' table.
 *
 * List of operations (made of incomings and outgoings)
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 03:40:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package classes
 */	
class OperationPeer extends BaseOperationPeer {

} // OperationPeer
