<?php

  // include base peer class
  require_once 'classes/om/BaseOutgoingPeer.php';
  
  // include object class
  include_once 'classes/Outgoing.php';


/**
 * Skeleton subclass for performing query and update operations on the 'outgoing' table.
 *
 * What is consumed by the community
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 03:40:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package classes
 */	
class OutgoingPeer extends BaseOutgoingPeer {
	
	public function computeTotal($person){
		
		$c = new Criteria();
		$c->add(OutgoingPeer::PERSONIDFK, $person);
		
		$outgoingsList = OutgoingPeer::doSelect($c);
		
		$total = 0;
		foreach ($outgoingsList as $outgoing)
			$total += $outgoing->computeWeightedPart();
		
		return $total;
		
	}

} // OutgoingPeer
