<?php

  // include base peer class
  require_once 'classes/om/BasePersonPeer.php';
  
  // include object class
  include_once 'classes/Person.php';


/**
 * Skeleton subclass for performing query and update operations on the 'person' table.
 *
 * List of person in the community
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 03:40:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package classes
 */	
class PersonPeer extends BasePersonPeer {
	
	public static function formOptionsArray () {
		
		$peopleList = self::doSelect(new Criteria());
		$peopleOptions = array();
		foreach($peopleList as $person)
			$peopleOptions[$person->getPersonId()] = $person->getPersonName();
		
		return $peopleOptions;
	}

} // PersonPeer
