<?php

require_once 'classes/om/BasePerson.php';


/**
 * Skeleton subclass for representing a row from the 'person' table.
 *
 * List of person in the community
 *
 * This class was autogenerated by Propel on:
 *
 * 11/06/05 03:40:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package classes
 */	
class Person extends BasePerson {
	
	public function getBalance() {
		
		$incomingsSum = IncomingPeer::computeTotal($this->getPersonId());
		$outgoingsSum = OutgoingPeer::computeTotal($this->getPersonId());
		
		return $incomingsSum - $outgoingsSum;
		
	}

} // Person
