<?php
// This file generated by Propel 1.5.4-dev convert-conf target
// from XML runtime conf file D:\www\money\propel-project\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'money' => 
    array (
      'adapter' => 'sqlite',
      'connection' => 
      array (
        'dsn' => 'sqlite:' . DATABASE_PATH,
      ),
    ),
    'default' => 'money',
  ),
  'log' => 
  array (
    'ident' => 'money',
    'level' => PROPEL_DEBUG_LEVEL,
  ),
  'generator_version' => '1.5.4-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-money-conf.php');
return $conf;